=== chaospheremk/public/MicrosoftEndpoints/DynamicGroupsSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "Name": {
                "type": "string"
            },
            "GroupObjectGUID": {
                "type": "string",
                "format": "uuid"
            },
            "Filter": {
                "type": "string"
            },
            "LDAPFilter": {
                "type": "string"
            },
            "SearchBase": {
                "type": "string"
            },
            "ObjectType": {
                "type": "string",
                "enum": [
                    "User",
                    "Computer"
                ]
            }
        },
        "required": [
            "Name",
            "GroupObjectGUID",
            "SearchBase",
            "ObjectType"
        ],
        "anyOf": [
            {
                "required": [
                    "Filter"
                ]
            },
            {
                "required": [
                    "LDAPFilter"
                ]
            }
        ],
        "additionalProperties": false
    }
}

=== chaospheremk/public/MicrosoftEndpoints/DynamicGroups.json
[
    {
        "Name": "DJM_ACL_AD_Dyn_City_Peoria",
        "GroupObjectGUID": "b741c587-65c5-46f5-9597-ff3b99aa0562",
        "Filter": "City -eq 'Peoria'",
        "LDAPFilter": "(l=Peoria)",
        "SearchBase": "OU=TestDynUsers,OU=MyUsers,DC=dougjohnson,DC=me",
        "ObjectType": "User"
    },
    {
        "Name": "DJM_ACL_AD_Dyn_City_Hell",
        "GroupObjectGUID": "4cd0114e-7ec2-44fc-8a1f-fe2c10c5db0f",
        "Filter": "City -eq 'Hell'",
        "LDAPFilter": "(l=Hell)",
        "SearchBase": "OU=TestDynUsers,OU=MyUsers,DC=dougjohnson,DC=me",
        "ObjectType": "User"
    },
    {
        "Name": "DJM_ACL_AD_Dyn_City_Roanoke",
        "GroupObjectGUID": "47e08fa9-a14d-4b67-a9c0-ad28cbe53b85",
        "Filter": "City -eq 'Roanoke'",
        "LDAPFilter": "(l=Roanoke)",
        "SearchBase": "OU=TestDynUsers,OU=MyUsers,DC=dougjohnson,DC=me",
        "ObjectType": "User"
    },
    {
        "Name": "DJM_ACL_AD_Dyn_City_Farmington",
        "GroupObjectGUID": "2a31d145-e597-401f-9016-7d5e7ce32331",
        "Filter": "City -eq 'Farmington'",
        "LDAPFilter": "(l=Farmington)",
        "SearchBase": "OU=TestDynUsers,OU=MyUsers,DC=dougjohnson,DC=me",
        "ObjectType": "User"
    },
    {
        "Name": "DJM_ACL_AD_Dyn_Location_Heaven",
        "GroupObjectGUID": "47d02f3d-6760-4328-a039-f40d5172baab",
        "Filter": "Location -eq 'Heaven'",
        "LDAPFilter": "(location=Heaven)",
        "SearchBase": "OU=MyComputers,DC=dougjohnson,DC=me",
        "ObjectType": "Computer"
    },
    {
        "Name": "DJM_ACL_AD_Dyn_Location_Closet",
        "GroupObjectGUID": "76f5fbda-9b01-4b88-bb6e-a0a507aeb637",
        "Filter": "Location -eq 'Closet'",
        "LDAPFilter": "(location=Closet)",
        "SearchBase": "OU=MyComputers,DC=dougjohnson,DC=me",
        "ObjectType": "Computer"
    },
    {
        "Name": "DJM_ACL_AD_Dyn_Location_Basement",
        "GroupObjectGUID": "7c0f9a5d-e673-4627-80a0-d0deb0d21485",
        "Filter": "Location -eq 'Basement'",
        "LDAPFilter": "(location=Basement)",
        "SearchBase": "OU=MyComputers,DC=dougjohnson,DC=me",
        "ObjectType": "Computer"
    },
    {
        "Name": "DJM_ACL_AD_Dyn_Location_FirstFloor",
        "GroupObjectGUID": "104e1d2b-197b-478e-8fb9-ecd18151a702",
        "Filter": "Location -eq 'First Floor'",
        "LDAPFilter": "(location=First Floor)",
        "SearchBase": "OU=MyComputers,DC=dougjohnson,DC=me",
        "ObjectType": "Computer"
    }
]
